service: star-logger

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1

  environment:
    repo: octocat/hello-worId
    phantUrl: https://data.sparkfun.com
    phantPublicKey: ''
    phantPrivateKey: ''

functions:
  star-logger:
    handler: handler.starLogger
    events:
      - schedule: rate(1 day)
